WebApplication1/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
	//Model for a Post
	public class Post
	{
		[Required]
		[Key]
		public int PostId { get; set; }

		[Required]
		[Display(Name = "Title")]
		[DataType(DataType.Text)]
		public string Title { get; set; }

		[Required]
		public DateTime Time { get; set; }

		[DataType(DataType.Upload)]
		[Display(Name = "Upload image")]
		//This will be a string of the file name of the post's picture
		public string ImageString { get; set; }

		[Display(Name = "Post content")]
		[DataType(DataType.MultilineText)]
		public string Content { get; set; }

		[Required]
		[ForeignKey("UserId")]
		public string UserId { get; set; }

		[Required]
		public ApplicationUser User { get; set; }

		public virtual List<Comment> Comments { get; set; }
	}
}

WebApplication1/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
	[Authorize(Policy = "Restricted")]
	public class PostsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly IHostingEnvironment _environment;

		public PostsController(ApplicationDbContext context,
			UserManager<ApplicationUser> userManager,
			IHostingEnvironment IHostingEnvironment)
		{
			_context = context;
			_userManager = userManager;
			_environment = IHostingEnvironment;
		}

		// GET: Posts/Index
		public async Task<IActionResult> Index()
		{
			List<Post> posts = await _context.Posts.ToListAsync();
			List<Post> SortedList = posts.OrderByDescending(o => o.Time).ToList();
			PostIndexViewModel viewModel = await BuildPostIndexViewModel(SortedList);
			return View(viewModel);
		}

		// GET: Posts/Details
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			PostDetailViewModel viewModel = await BuildDetailViewModel(id);

			if (viewModel == null || viewModel.Post == null || viewModel.Post.User == null)
			{
				return NotFound();
			}
			return View(viewModel);
		}

		//POST/Details
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Details(
			[Bind("CommentText,CommentUserName,CommentUserId,CommentPostId")] PostDetailViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				if (viewModel.CommentText != null)
				{
					await AddComment(viewModel);
				}
			}
			viewModel = await BuildDetailViewModel(viewModel.CommentPostId);

			return View(viewModel);
		}

		// GET: Posts/Create
		[Authorize(Policy = "Poster")]
		public async Task<IActionResult> Create()
		{
			ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
			PostCreateViewModel viewModel = new PostCreateViewModel();
			return View(viewModel);
		}

		//POST: Posts/Create
		[HttpPost]
		[Authorize(Policy = "Poster")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("PostTitle,PostContent,PostImageString")] PostCreateViewModel viewModel, IFormFile file)
		{
			if (ModelState.IsValid)
			{
				ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);

				Post post = new Post
				{
					Title = viewModel.PostTitle,
					Time = DateTime.Now,
					Content = viewModel.PostContent,
					User = user,
					UserId = user.Id,
				};

				_context.Add(post);
				await _context.SaveChangesAsync();

				if (file != null)
				{
					string fileId = await SaveImage(file, post.PostId.ToString());
					post.ImageString = fileId;
					_context.Update(post);
					await _context.SaveChangesAsync();
				}
				return RedirectToAction(nameof(Index));
			}
			else
			{
				return View(viewModel);
			}
		}

		// GET: Posts/Edit
		[Authorize(Policy = "Poster")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Post post = await _context.Posts.FindAsync(id);
			if (post == null)
			{
				return NotFound();
			}

			PostEditViewModel viewModel = new PostEditViewModel
			{
				PostId = post.PostId,
				ImageString = post.ImageString,
				PostContent = post.Content,
				PostTitle = post.Title
			};

			return View(viewModel);
		}

		// POST: Posts/Edit
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "Poster")]
		public async Task<IActionResult> Edit([Bind("PostTitle,PostContent,ImageString, PostId")] PostEditViewModel viewModel, IFormFile file)
		{
			Post post = await _context.Posts.FindAsync(viewModel.PostId);

			if (ModelState.IsValid)
			{
				try
				{
					if (post != null)
					{
						post.Title = viewModel.PostTitle;
						if (viewModel.PostContent == null)
						{
							//Content can be empty, but not null
							viewModel.PostContent = "";
						}
						post.Content = viewModel.PostContent;
						_context.Update(post);
						await _context.SaveChangesAsync();
						if (file != null)
						{

							if (post.ImageString != null)
							{
								DeletePostImage(post);
							}
							post.ImageString = await SaveImage(file, post.PostId.ToString());
							viewModel.ImageString = post.ImageString;
							_context.Update(post);
							await _context.SaveChangesAsync();
							return View(viewModel);
						}
						else if (viewModel.ImageString == null && post.ImageString != null)
						{
							DeletePostImage(post);
							post.ImageString = null;
							_context.Update(post);
							await _context.SaveChangesAsync();
							return View(viewModel);
						}
					}

				}
				catch (DbUpdateConcurrencyException)
				{
					if (!PostExists(viewModel.PostId))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				//Returns user to the details of their new post
				return RedirectToAction("Details/" + viewModel.PostId);
			}
			return View(viewModel);
		}

		// GET: Posts/Delete
		[Authorize(Policy = "Poster")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Post post = await _context.Posts
				.FirstOrDefaultAsync(m => m.PostId == id);
			if (post == null)
			{
				return NotFound();
			}

			return View(post);
		}

		// POST: Posts/Delete
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "Poster")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			Post post = await _context.Posts.FindAsync(id);
			if (post.ImageString != null)
			{
				DeletePostImage(post);
			}
			_context.Posts.Remove(post);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		// GET: Posts/DeleteComment
		[Authorize(Policy = "User")]
		public async Task<IActionResult> DeleteComment(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			Comment comment = await _context.Comments
				.FirstOrDefaultAsync(m => m.CommentId == id);
			if (comment == null)
			{
				return NotFound();
			}

			int postId = comment.PostId;

			_context.Comments.Remove(comment);
			await _context.SaveChangesAsync();
			return RedirectToAction("Details/" + postId);
		}

		// POST: Posts/EditComment
		[HttpPost, ActionName("EditComment")]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "User")]
		public async Task<IActionResult> EditComment([Bind("EditCommentId, CommentText, CommentPostId")] PostIndexViewModel viewModel)
		{
			Comment comment = await _context.Comments.FindAsync(viewModel.EditCommentId);
			if (viewModel.CommentText != null)
			{
				comment.Text = viewModel.CommentText;
				await _context.SaveChangesAsync();
			}

			string postId = viewModel.CommentPostId.ToString();
			return RedirectToAction("Details/" + postId + "#comments");
		}

		//Builds PostIndexViewModel
		private async Task<PostIndexViewModel> BuildPostIndexViewModel(List<Post> SortedList)
		{
			//I had previously used a foreach loop, but research shows that a for loop is less computationally expensive
			for (int i = 0; i < SortedList.Count; i++)
			{
				Post post = SortedList[i];
				//Need to load user and comment data into each post manually
				//They are null by deafult which I think is due to lazy loading
				post.User = await _userManager.FindByIdAsync(post.UserId);
				post.Comments = _context.Comments.Where(d => d.PostId == post.PostId).ToList();
				foreach (Comment comment in post.Comments)
				{
					comment.User = await _userManager.FindByIdAsync(comment.UserId);
				}
			}

			ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);

			PostIndexViewModel viewModel = new PostIndexViewModel
			{
				User = user,
				Posts = SortedList,
				UserClaim = await GetUserClaimAsync(user)
			};
			return viewModel;
		}

		//Saves an uploaded IFormFile to the server for a post image
		private async Task<string> SaveImage(IFormFile file, string postId)
		{
			string uploads = Path.Combine(_environment.WebRootPath, "images/posts");
			string fileId = postId + Path.GetExtension(file.FileName);
			string filePath = Path.Combine(uploads, fileId);
			FileStream fs = new FileStream(filePath, FileMode.Create);
			await file.CopyToAsync(fs);
			fs.Close();
			return fileId;
		}

		//Deletes an image from a post
		private void DeletePostImage(Post post)
		{
			string uploads = Path.Combine(_environment.WebRootPath, "images/posts");
			string path = Path.Combine(uploads, post.ImageString);
			System.IO.File.Delete(path);
		}

		//Checks if a post exists
		private bool PostExists(int id)
		{
			return _context.Posts.Any(e => e.PostId == id);
		}

		//Builds the ViewModel for viewing the details of a post
		private async Task<PostDetailViewModel> BuildDetailViewModel(int? id)
		{
			Post post = await _context.Posts.FirstOrDefaultAsync(m => m.PostId == id);

			if (post != null)
			{
				PostDetailViewModel viewModel = new PostDetailViewModel
				{
					Post = post
				};
				viewModel.Post.User = await _userManager.FindByIdAsync(viewModel.Post.UserId);
				viewModel.Comments = await _context.Comments.Where(m => m.PostId == id).ToListAsync();
				foreach (Comment c in viewModel.Comments)
				{
					c.User = await _userManager.FindByIdAsync(c.UserId);
				}

				ApplicationUser u = await _userManager.GetUserAsync(HttpContext.User);
				viewModel.User = u;
				viewModel.UserClaim = await GetUserClaimAsync(u);
				return viewModel;
			}
			return null;
		}

		//Gets the claims of a User u
		private async Task<string> GetUserClaimAsync(ApplicationUser u)
		{
			Claim admin = new Claim("IsAdmin", "true");

WebApplication1/Views/Posts/Create.cshtml
@model WebApplication1.ViewModels.PostCreateViewModel

@{
	ViewData["Title"] = "Create";
}

<h2>Create a new post!</h2>

<div class="row">
	<div>
		<form asp-action="Create" enctype="multipart/form-data">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group col-md-4 clear-both">
				<label asp-for="PostTitle" class="control-label"></label>
				<input asp-for="PostTitle" class="form-control" />
				<span asp-validation-for="PostTitle" class="text-danger"></span>
			</div>
			<div class="form-group col-md-8 clear-both">
				<label asp-for="PostContent" class="control-label"></label>
				<textarea asp-for="PostContent" class="form-control col-md-8" rows="3"></textarea>
				<span asp-validation-for="PostContent" class="text-danger"></span>
			</div>

			<div class="form-group col-md-4 clear-both">
				<label asp-for="PostImage" class="control-label clear-both"></label>
				<input type="file" accept="image/*" onchange="uploadCheck()" asp-for="PostImage" name="file" />
				<span asp-validation-for="PostImage" class="text-danger"></span>
			</div>
			<div class="form-group clear-both col-md-2">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>
<script type="text/javascript">
	//This checks if the file selected by the user is acceptable based on it's file extension
	function uploadCheck() {
		var image = document.getElementById("PostImage").value;
		var ext = getExtension(image);

		var extensionLists = ['jpg', 'jpeg', 'svg', 'gif', 'bmp', 'png', 'JPG', 'JPEG', 'SVG', 'GIF', 'BMP', 'PNG'];

		var contains = (extensionLists.indexOf(ext) > -1);

		if (!contains) {
			alert("Sorry, only images of types: " + extensionLists.toString() + " are allowed");
			document.getElementById("PostImage").value = "";
		}
	}

	//This gets the extension from a file name
	function getExtension(filename) {
		var parts = filename.split('.');
		return parts[parts.length - 1];
	}
</script>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Posts/Delete.cshtml
@model WebApplication1.Models.Post

@{
	ViewData["Title"] = "Delete";
}

<div>
	<h3 class="delete-h3">Are you sure you want to delete this post?</h3>

	<div class="delete-box">
		<table>
			<tbody>
				<tr>
					<td>
						@if (Model.ImageString != null)
						{
							string location = "~/images/posts/" + Model.ImageString;
							<img src="@Url.Content(location)" class="delete-img img-responsive center-block" alt="@Model.Title" />
						}

					</td>
					<td>
						<div>
							<h4>@Model.Title</h4>
						</div>
						<div>
							<h5>@Model.Content</h5>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<form asp-action="Delete">
		<div class="center-box"> 
			<input type="hidden" asp-for="PostId" />
			<input type="submit" value="Delete" class="btn btn-danger" />
			<a asp-action="Index" class="btn btn-default">Back to List</a>
		</div>
	</form>
</div>

WebApplication1/Views/Posts/Details.cshtml
@model WebApplication1.ViewModels.PostDetailViewModel;

@{
	ViewData["Title"] = Model.Post.Title;
}

<div class="empty-table">

	<div class="gap"></div>
	<div class="details-bar">
		<a asp-action="Index" class="back-link">
			<svg class="back-icon" viewBox="0 0 512 512">
				<path d="M480 224H128L294.06 57.94a33.94 33.94 0 0 0-48-48L0 256l48 48 198.06 198.06a33.94 33.94 0 0 0 48-48L128 288h352a32 32 0 0 0 32-32 32 32 0 0 0-32-32z" />
			</svg>
		</a>
		<h4 class="post-text">
			Post
		</h4>
	</div>

</div>

<table class="table">
	<tbody>
		<tr class="whole-post">
			<td class="post-avatar">
				<div class="stream_top">
					<div class="stream_avatar">
						@{
							string profilePictureLocation = "";
							if (Model.Post.User.AvatarString == null)
							{
								profilePictureLocation = "~/images/user.png";
							}
							else
							{
								profilePictureLocation = "~/images/avatars/" + Model.Post.User.AvatarString;
							}
						}
						<div style='background:url(@Url.Content(profilePictureLocation))'></div>
					</div>
				</div>
			</td>
			<td>
				<div>
					<div>

						<h4>@Model.Post.User.Name</h4>

						<h6>@Model.GetTimeSpan(Model.Post.Time)</h6>

						@{
							bool b = false;
							if (Model.UserClaim == ("admin"))
							{
								b = true;
							}
							if (Model.User.Id == Model.Post.UserId)
							{
								if ((Model.UserClaim == "poster") || (Model.UserClaim == "user"))
								{
									b = true;
								}
							}
						}

						@if (b)
						{
							<div class="float-right">
								<table>
									<tr>
										<td>
											<a asp-action="Edit" class="dont-wrap" asp-route-id="@Model.Post.PostId">Edit post</a>
										</td>
									</tr>
									<tr>
										<td>
											<a asp-action="Delete" class="dont-wrap" asp-route-id="@Model.Post.PostId"> Delete post </a>
										</td>
									</tr>
								</table>
							</div>
						}
						<h2>@Model.Post.Title</h2>
						<p>@Model.Post.Content</p>
						@if (Model.Post.ImageString != null)
						{
							string location = "~/images/posts/" + Model.Post.ImageString;
							<img src="@Url.Content(location)" class="img-responsive center-block" alt="@Model.Post.Title" />
						}
					</div>
					<div id="comments" class="comments">
						@if (Model.Comments != null && Model.Comments.Count >= 1)
						{
							<h5>Most recent comment</h5>
							foreach (Comment c in Model.Comments)
							{
								<table class="others_comments">
									<tr>
										<td class="comment_avatar">
											@{
												string commentProfileLocation = "";

												if (c.User.AvatarString == null)
												{
													commentProfileLocation = "~/images/user.png";
												}
												else
												{
													commentProfileLocation = "~/images/avatars/" + c.User.AvatarString;
												}
											}
											<div style='background:url(@Url.Content(commentProfileLocation))'></div>
										</td>
										<td class="comment-content">
											<div class="full-width">
												<h4 class="float-left">@c.User.Name</h4>
												<h6 class="float-left comment-time">@Model.GetTimeSpan(c.Time)</h6>
											</div>
											@{string id1 = c.CommentId + "string"; }
											@{string id2 = c.CommentId + "input"; }


											<div class="comment-text" id="@id1">
												<p>@c.Text</p>
											</div>

											<form asp-action="EditComment" id="@id2" class="gone">
												<div class="add-comment">
													<div class="col-md-4">
														<input type="hidden" asp-for="CommentPostId" value="@c.PostId" />
														<input type="hidden" asp-for="EditCommentId" value="@c.CommentId" />
														<input asp-for="CommentText" value="@c.Text" class="form-control" />
														<span asp-validation-for="CommentText" class="text-danger"></span>
													</div>
													<input type="submit" value="Edit Comment" class="btn btn-default" />
												</div>
											</form>
										</td>



										@{
											bool canEdit = false;
											if (Model.UserClaim == ("admin"))
											{
												canEdit = true;
											}
											if (c.UserId == Model.User.Id)
											{
												if ((Model.UserClaim == "poster") || (Model.UserClaim == "user"))
												{
													canEdit = true;
												}
											}
										}

										@if (canEdit)
										{
											<td class="float-right dont-wrap">
												<div onclick="editComment(@c.CommentId)" class="clickable clear-both">Edit Comment</div>
												<div onclick="deleteConfirm(@c.CommentId)" class="clickable clear-both">Delete Comment</div>

											</td>
										}
									</tr>
								</table>
							}
						}
						else
						{
							<h5>No Comments...yet.</h5>
						}

						@if (Model.UserClaim != "restricted")
						{
							<h5>Add Comment</h5>

							<table class="others_comments">
								<tr>
									<td class="comment_avatar">
										@{
											string userProfileLocation = "";
											if (Model.User.AvatarString == null)
											{
												userProfileLocation = "~/images/user.png";
											}
											else
											{
												userProfileLocation = "~/images/avatars/" + Model.User.AvatarString;
											}
										}
										<div style='background:url(@Url.Content(userProfileLocation))'></div>
									</td>
									<td class="comment-content">
										<div class="full-width">
												<h4 class="float-left">@Model.User.Name</h4>
										</div>
										<form class="comment-text col-lg-10" asp-action="Details">
											<div asp-validation-summary="ModelOnly" class="text-danger"></div>
											<input type="hidden" asp-for="CommentUserName" value="@Model.User.UserName" />
											<input type="hidden" asp-for="CommentUserId" value="@Model.User.Id" />
											<input type="hidden" asp-for="CommentPostId" value="@Model.Post.PostId" />
											<div class="add-comment">
												<div class="col-md-4">
													<input asp-for="CommentText" value="" class="form-control" />
													<span asp-validation-for="CommentText" class="text-danger"></span>
												</div>
												<input type="submit" value="Add Comment" class="btn btn-default" />
											</div>
										</form>
									</td>
								</tr>
							</table>
						}
					</div>
				</div>
			</td>
		</tr>
		<tr class="gap"></tr>
	</tbody>
</table>

<script type="text/javascript">
	function deleteConfirm(Id) {
		var r = confirm("Are you sure you want to delete this comment?");
		if (r == true) {
			var url = '@Url.Action("DeleteComment", "Posts")'+"/"+Id;
			window.location.href = url;
		}
	}

	function editComment(id) {
		var element = document.getElementById(id+"string");
		element.parentNode.removeChild(element);
		var element2 = document.getElementById(id + "input");
		element2.style.display = "block";
	}
</script>

WebApplication1/Views/Posts/Index.cshtml
@model WebApplication1.ViewModels.PostIndexViewModel;
@{
	ViewData["Title"] = "FruitStream";
}
<div>
	<h1>FruitStream</h1>
	@if ((Model.UserClaim == "admin") || (Model.UserClaim == "poster"))
	{
		<a class="btn btn-default float-right create-button" asp-action="Create">
			<svg viewBox="0 0 512 512" class="plus">
				<path d="M464 304H304v160a48 48 0 0 1-48 48 48 48 0 0 1-48-48V304H48a48 48 0 0 1-48-48 48 48 0 0 1 48-48h160V48a48 48 0 0 1 48-48 48 48 0 0 1 48 48v160h160a48 48 0 0 1 48 48 48 48 0 0 1-48 48z" />
			</svg>
			Create some of that delicious content
		</a>
	}
</div>
<table class="table table-responsive">
	<tbody>
		@foreach (var item in Model.Posts)
		{
			<tr class="whole-post">
				<td class="post-avatar" onclick="loadPost(@item.PostId)">
					<div class="stream_top">
						<a asp-action="Details" asp-route-id="@item.PostId" class="post">
							<div class="stream_avatar">
								@{
									string profilePictureLocation = "";
									if (item.User.AvatarString == null)
									{
										profilePictureLocation = "~/images/user.png";
									}
									else
									{
										profilePictureLocation = "~/images/avatars/" + item.User.AvatarString;
									}
								}
								<div style='background:url(@Url.Content(profilePictureLocation))'></div>
							</div>
						</a>
					</div>
				</td>
				<td>
					<div>
						<a asp-action="Details" asp-route-id="@item.PostId" class="post">
							<h4>@item.User.Name</h4>

							<h6>@Model.GetTimeSpan(item.Time)</h6>

							@{
								//This determines if the user can access the edit and delete functionality
								bool b = false;
								if (Model.UserClaim == ("admin"))
								{
									b = true;
								}
								if (Model.User.Id == item.UserId)
								{
									if ((Model.UserClaim == "poster") || (Model.UserClaim == "user"))
									{
										b = true;
									}
								}
							}
							@if (b)
							{
								<div class="float-right">
									<table>
										<tr>
											<td>
												<a asp-action="Edit" class="dont-wrap" asp-route-id="@item.PostId">Edit post</a>
											</td>
										</tr>
										<tr>
											<td>
												<a asp-action="Delete" class="dont-wrap" asp-route-id="@item.PostId"> Delete post </a>
											</td>
										</tr>
									</table>
								</div>
							}
							<h2>@item.Title</h2>
							<p>@item.Content</p>
							@if (item.ImageString != null)
							{
								//This shows the image for the post, if one exists.
								string location = "~/images/posts/" + item.ImageString;
								<img src="@Url.Content(location)" class="img-responsive center-block" alt="@item.Title" />
							}
						</a>

						<div class="comments">
							<h4>Most recent comment</h4>

							@if (item.Comments != null && item.Comments.Count >= 1)
							{
								//This gets and shows the most recent comment only
								Comment c;
								if (item.Comments.Count == 1)
								{
									c = item.Comments[0];
								}
								else
								{
									c = item.Comments[item.Comments.Count - 1];
								}
								<table class="others_comments">
									<tr>
										<td class="comment_avatar">
											@{
												//Finds the avatar of the comment poster and displays it, if it exists
												string commentProfileLocation = "";

												if (c.User.AvatarString == null)
												{
													commentProfileLocation = "~/images/user.png";
												}
												else
												{
													commentProfileLocation = "~/images/avatars/" + c.User.AvatarString;
												}
											}
											@*
												For profile images, I have used a div with the image as the background.
												This gives more flexibilty for profile iamges of strange sizes and
												keeeping them consistently the same size. However, it also means I can't
												use the alt tag for accessibility.
											*@
											<div style='background:url(@Url.Content(commentProfileLocation))'></div>
										</td>
										<td class="comment-content">
											<div class="full-width">
												<h4 class="float-left">@c.User.Name</h4>
												<h6 class="float-left comment-time">@Model.GetTimeSpan(c.Time)</h6>
											</div>
											@{string id1 = c.CommentId + "string"; }
											@{string id2 = c.CommentId + "input"; }


											<div class="comment-text" id="@id1">
												<p>@c.Text</p>
											</div>

											<form asp-action="EditComment" id="@id2" class="gone">
												<div class="add-comment">
													<div class="col-md-4">
														<input type="hidden" asp-for="CommentPostId" value="@c.PostId" />
														<input type="hidden" asp-for="EditCommentId" value="@c.CommentId" />
														<input asp-for="CommentText" value="" class="form-control" />
														<span asp-validation-for="CommentText" class="text-danger"></span>
													</div>
													<input type="submit" value="Edit Comment" class="btn btn-default" />
												</div>
											</form>
										</td>
										@if (c.UserId == Model.User.Id)
										{
											<td class="float-right dont-wrap">
												<div onclick="editComment(@c.CommentId)" class="clickable clear-both">Edit Comment</div>
												<div onclick="deleteConfirm(@c.CommentId)" class="clickable clear-both">Delete Comment</div>
											</td>
										}
									</tr>
									<tr>
										<td></td>
										<td>
											<h5 class="clear-both">
												<a asp-action="Details" asp-fragment="Comments" asp-route-id="@item.PostId">
													View all comments
												</a>
											</h5>
										</td>
									</tr>
								</table>

							}
							else
							{
								<h5 class="light-grey">
									No Comments...yet.
								</h5>
							}
							@if (Model.UserClaim != "restricted")
							{
								<h4>Add Comment</h4>

								<table class="others_comments">
									<tr>
										<td class="comment_avatar">
											@{
												string userProfileLocation = "";
												if (Model.User.AvatarString == null)
												{
													userProfileLocation = "~/images/user.png";
												}
												else
												{
													userProfileLocation = "~/images/avatars/" + Model.User.AvatarString;
												}
											}
											<div style='background:url(@Url.Content(userProfileLocation))'></div>
										</td>
										<td class="comment-content">
											<div class="full-width">
												<h4 class="float-left">@Model.User.Name</h4>
											</div>
											<form class="comment-text col-lg-10" asp-action="Details">
												<div asp-validation-summary="ModelOnly" class="text-danger"></div>
												<input type="hidden" asp-for="CommentUserName" value="@Model.User.UserName" />
												<input type="hidden" asp-for="CommentUserId" value="@Model.User.Id" />
												<input type="hidden" asp-for="CommentPostId" value="@item.PostId" />
												<div class="add-comment">
													<div class="col-md-4">
														<input asp-for="CommentText" class="form-control" />
														<span asp-validation-for="CommentText" class="text-danger"></span>
													</div>
													<input type="submit" value="Add Comment" id="@item.PostId" class="btn btn-default" />
												</div>
											</form>
										</td>
									</tr>
								</table>
							}
						</div>
					</div>
				</td>
			</tr>
			<tr class="gap"></tr>
		}

	</tbody>
</table>
<script type="text/javascript">
	function deleteConfirm(Id) {
		//This confirms if the user wants to delete a comment
		var r = confirm("Are you sure you want to delete this comment?");
		if (r == true) {
			var url = '@Url.Action("DeleteComment", "Posts")'+"/"+Id;
			window.location.href = url;
		}
	}

	//This shows the textbox to edit a comment
	function editComment(id) {
		var element = document.getElementById(id + "string");
		element.parentNode.removeChild(element);
		var element2 = document.getElementById(id + "input");
		element2.style.display = "block";
	}

</script>